### ISSUE TITLE
interpreter string to decimal if in Source and target

### ISSUE THREAD

**Issue by tontonpolak** [anyvado/sql#1]
Hi,
DECLARE @options NVARCHAR(MAX) = '{"update_array":0,"update_null":0}',
		@target NVARCHAR(MAX) = '{"bool":true, "text":"hello", "arr":[0,1,2],"product_version": "1.0"}',
		@SOURCE NVARCHAR(MAX) = '{"bool":false, "text":null, "arr":[0,3,4],"iamnull":null,"product_version": "1.0"}'
 
PRINT dbo.udf_native_json_merge(@target, @SOURCE, @options)

retunr ==> {"bool":false, "text":null, "arr":[0,1,2,0,3,4],"product_version": 1.000000000000000e+000,"iamnull":null}

product_version has been changed in format and value
originally String, after decimal rounded

**Comment by anyvado** [comment]
Hi, thanks for reporting. Issue fixed in latest version.
